language: python
python:
  - "2.7"
env:
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=pypy
install:
  - pip install coveralls tox
script:
  - tox -e $TOX_ENV
  - python setup.py check -r
after_success:
  - coveralls --verbose
